# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shizai_pro_development

test:
  <<: *default
  database: shizai_pro_test

production:
  primary:
    <<: *default
    database: shizai_pro_production
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV["DATABASE_HOST"] %>
  cache:
    <<: *default
    database: shizai_pro_production_cache
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV["DATABASE_HOST"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: shizai_pro_production_queue
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV["DATABASE_HOST"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: shizai_pro_production_cable
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    host: <%= ENV["DATABASE_HOST"] %>
    migrations_paths: db/cable_migrate
